# Simple workflow for deploying a React app to GitHub Pages
name: Deploy React App

on:
  push:
    branches:
      - main # Or whatever your default branch is

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use a recent Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # The directory that contains the build output
          cname: your-domain.com # Optional: if you have a custom domain
